### ISSUE TITLE
Game URL's do not map to games correctly

### ISSUE THREAD

**Issue by boredompwndu** [danbuis/full_thrust_pbp#4]
game 1234 goes to https://ambitious-island-0dd4bd40f.2.azurestaticapps.net/game/7bf4c6f4-f7ba-483f-99f3-9eb2d365af0a

This link doesn't work

**Comment by boredompwndu** [comment]
1234 theoretically links to \*something\*?

**Comment by danbuis** [comment]
Leaving this open to update documentation.

Its likely because this is a "single page app" and all the diff pages you might be seeing are a lie.  Gotta start at the home page and then navigate around internally, otherwise it doesn't know what the flip you are doing.

Gotta make it clearer that when creating a new you game you NEED to keep that alpha numberic thing, and that the alphanumeric is the game id, not the name of the game.

I am not dealing with enforcing unique game names.  Not when there is a perfectly fine unique id func built right into the language that I can use to store and retrieve items.

**Comment by boredompwndu** [comment]
Sure. Welcome to user experience I guess
